# -*- coding: utf-8 -*-
"""hackathon.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16pslmetpgEdOrbWPNeKgXbuiV8RRC7yz
"""

! pip3 install --upgrade --user google-cloud-aiplatform

# Restart kernel after installs so that your environment can access the new packages
import IPython
import time

app = IPython.Application.instance()
app.kernel.do_shutdown(True)

import sys

# Additional authentication is required for Google Colab
if "google.colab" in sys.modules:
    # Authenticate user to Google Cloud
    from google.colab import auth

    auth.authenticate_user()

# Define project information
# You can use Colab secrets if you wish to keep it hidden
from google.colab import userdata
#my_project = userdata.get('GCP_PROJECT_ID')

PROJECT_ID = "genaigenesis "  # @param {type:"string"}
LOCATION = "us-central1"  # @param {type:"string"}

#print(PROJECT_ID)

# Initialize Vertex AI
import vertexai

vertexai.init(project=PROJECT_ID, location=LOCATION)

from vertexai.generative_models import (
    GenerationConfig,
    GenerativeModel,
    HarmCategory,
    HarmBlockThreshold,
    Image,
    Part,
)

import google.generativeai as genai

multimodal_model = GenerativeModel("gemini-1.0-pro-vision")
#images, text, audio as input
#text/code as output

response = multimodal_model.generate_content("What is the meaning of life?")
print(response)